//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.InterfaceUser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITI.InterfaceUser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attaquant {
            get {
                object obj = ResourceManager.GetObject("attaquant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Board11x11 {
            get {
                object obj = ResourceManager.GetObject("Board11x11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Board13x13 {
            get {
                object obj = ResourceManager.GetObject("Board13x13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Board7x7 {
            get {
                object obj = ResourceManager.GetObject("Board7x7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Board9x9 {
            get {
                object obj = ResourceManager.GetObject("Board9x9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Case_en_bois {
            get {
                object obj = ResourceManager.GetObject("Case_en_bois", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Case_en_bois_effet {
            get {
                object obj = ResourceManager.GetObject("Case_en_bois_effet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CaseInterdite {
            get {
                object obj = ResourceManager.GetObject("CaseInterdite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap défenseur {
            get {
                object obj = ResourceManager.GetObject("défenseur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. La famille des jeux de Tafl regroupe différents jeux possédant plusieurs caractéristiques communes : 
        ///
        ///	- Un plateau de jeu carré. 
        ///	- Des cases marquées symétriquement. 	
        ///	- Des forces inégales. 
        ///	- Un principe de prise par encadrement. 
        ///	- Des objectifs de jeux différents. 
        ///	- Une pièce particulière, le roi. 
        ///
        ///
        ///2. Le but des jeux de Tafl est de : 
        ///
        ///	- Pour l’attaquant, de prendre le roi adverse. 
        ///
        ///	- Pour le défenseur, d’amener le roi dans une forteresse : les cases dans les coins du plat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Initialisation_d_un_plateau {
            get {
                return ResourceManager.GetString("Initialisation_d_un_plateau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Victoire du défenseur :
        ///
        ///	Pour gagner, le défenseur blanc doit amener son roi sur l&apos;une des quatre forteresses situées
        ///	aux coins. 
        ///
        ///2. Victoire de l&apos;attaquant ; 
        ///
        ///	Pour gagner, l&apos;attaquant noir doit capturer le roi. .
        /// </summary>
        internal static string Les_conditions_de_victoires {
            get {
                return ResourceManager.GetString("Les_conditions_de_victoires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Capture de pion
        ///
        ///	- Un pion est battu et retiré du tablier s&apos;il se retrouve, dans un alignement orthogonal, 
        ///	  pris en tenailles par deux adversaires sur deux côtés opposés de la case qu&apos;il occupe.
        ///
        ///	- Le roi peut participer à battre un pion adverse mais on ne peut pas le battre de la même
        ///	  façon.
        ///
        ///	- Un pion est également battu s&apos;il se retrouve pris en tenailles par un adversaire et une 
        ///	  forteresse.  
        ///	  Il est possible de prendre deux ou trois pions en déplaçant un seul pion. 
        ///
        ///	- Un  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Les_différentes_types_de_captures {
            get {
                return ResourceManager.GetString("Les_différentes_types_de_captures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Le joueur attaquant joue en premier. 
        ///
        ///- Les pions se déplacent orthogonalement vers un emplacement libre, d&apos;une ou plusieurs cases, comme 
        ///  la tour au jeu d&apos;échecs. 
        ///
        ///- Toutes les cases empruntées lors du déplacement doivent être libres. 
        ///
        ///- Aucun autre pion que le Roi ne peut accéder aux quatre forteresses situées aux coins, ni à la 
        ///  forteresse centrale parfois appelée trône. 
        ///  Mais ils peuvent passer au-dessus de la case centrale si elle est libre. .
        /// </summary>
        internal static string Les_pions {
            get {
                return ResourceManager.GetString("Les_pions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PionBlanc {
            get {
                object obj = ResourceManager.GetObject("PionBlanc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PionNoir {
            get {
                object obj = ResourceManager.GetObject("PionNoir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PionRoi {
            get {
                object obj = ResourceManager.GetObject("PionRoi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TableDeTyr1 {
            get {
                object obj = ResourceManager.GetObject("TableDeTyr1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Victoire {
            get {
                object obj = ResourceManager.GetObject("Victoire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
